name: BuildCheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: [ubuntu-22.04, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose  --profile release-lto

  windows:
    runs-on: [windows-2019, windows-2022]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose  --profile release-lto

  macos:
    runs-on: [macos-13, macos-14]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose  --profile release-lto
